---
- name: Ensure config directory exists
  file:
    path: /etc/keepalived
    state: directory

- name: Write keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  register: config

- name: Write check_apiserver.sh
  template:
    src: check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh
    mode: 0755
  register: script

- name: Write static Pod manifest
  template:
    src: keepalived.yaml.j2
    dest: /etc/kubernetes/manifests/keepalived.yaml
