---
- name: Ensure config directory exists
  file:
    path: /etc/keepalived
    state: directory

- name: Write keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  register: config

- name: Write check_apiserver_v4.sh
  template:
    src: check_apiserver_v4.sh.j2
    dest: /etc/keepalived/check_apiserver_v4.sh
    mode: 0755
  register: script_v4

- name: Write check_apiserver_v6.sh
  template:
    src: check_apiserver_v6.sh.j2
    dest: /etc/keepalived/check_apiserver_v6.sh
    mode: 0755
  register: script_v6
  when: keepalived_kube_vip_v6 is defined

- name: Write static Pod manifest
  template:
    src: keepalived.yaml.j2
    dest: /etc/kubernetes/manifests/keepalived.yaml
